# daemon runs in the background
# run something like tail /var/log/bitcoinultrasd/current to see the status
# be sure to run with volumes, ie:
# docker run -v $(pwd)/bitcoinultrasd:/var/lib/bitcoinultrasd -v $(pwd)/wallet:/home/bitcoinultras --rm -ti bitcoinultras:latest
FROM ubuntu:16.04

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

ADD https://github.com/just-containers/socklog-overlay/releases/download/v2.1.0-0/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

COPY . /src/bitcoinultras


# install build dependencies
# checkout the latest tag
# build and install
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python-dev \
      gcc-4.9 \
      g++-4.9 \
      git cmake \
      libboost1.58-all-dev && \
    cd /src/bitcoinultras && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. && \
    make -j$(nproc) && \
    mkdir -p /usr/local/bin && \
    cp src/TurtleCoind /usr/local/bin/TurtleCoind && \
    cp src/walletd /usr/local/bin/walletd && \
    cp src/zedwallet /usr/local/bin/zedwallet && \
    cp src/miner /usr/local/bin/miner && \
    strip /usr/local/bin/TurtleCoind && \
    strip /usr/local/bin/walletd && \
    strip /usr/local/bin/zedwallet && \
    strip /usr/local/bin/miner && \
    cd / && \
    rm -rf /src/bitcoinultras && \
    apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost1.58-all-dev librocksdb-dev && \
    apt-get autoremove -y && \
    apt-get install -y  \
      libboost-system1.58.0 \
      libboost-filesystem1.58.0 \
      libboost-thread1.58.0 \
      libboost-date-time1.58.0 \
      libboost-chrono1.58.0 \
      libboost-regex1.58.0 \
      libboost-serialization1.58.0 \
      libboost-program-options1.58.0 \
      libicu55

# setup the bitcoinultrasd service
RUN useradd -r -s /usr/sbin/nologin -m -d /var/lib/bitcoinultrasd bitcoinultrasd && \
    useradd -s /bin/bash -m -d /home/bitcoinultras bitcoinultras && \
    mkdir -p /etc/services.d/bitcoinultrasd/log && \
    mkdir -p /var/log/bitcoinultrasd && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/bitcoinultrasd/run && \
    echo "fdmove -c 2 1" >> /etc/services.d/bitcoinultrasd/run && \
    echo "cd /var/lib/bitcoinultrasd" >> /etc/services.d/bitcoinultrasd/run && \
    echo "export HOME /var/lib/bitcoinultrasd" >> /etc/services.d/bitcoinultrasd/run && \
    echo "s6-setuidgid bitcoinultrasd /usr/local/bin/TurtleCoind" >> /etc/services.d/bitcoinultrasd/run && \
    chmod +x /etc/services.d/bitcoinultrasd/run && \
    chown nobody:nogroup /var/log/bitcoinultrasd && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/bitcoinultrasd/log/run && \
    echo "s6-setuidgid nobody" >> /etc/services.d/bitcoinultrasd/log/run && \
    echo "s6-log -bp -- n20 s1000000 /var/log/bitcoinultrasd" >> /etc/services.d/bitcoinultrasd/log/run && \
    chmod +x /etc/services.d/bitcoinultrasd/log/run && \
    echo "/var/lib/bitcoinultrasd true bitcoinultrasd 0644 0755" > /etc/fix-attrs.d/bitcoinultrasd-home && \
    echo "/home/bitcoinultras true bitcoinultras 0644 0755" > /etc/fix-attrs.d/bitcoinultras-home && \
    echo "/var/log/bitcoinultrasd true nobody 0644 0755" > /etc/fix-attrs.d/bitcoinultrasd-logs

VOLUME ["/var/lib/bitcoinultrasd", "/home/bitcoinultras","/var/log/bitcoinultrasd"]

ENTRYPOINT ["/init"]
CMD ["/usr/bin/execlineb", "-P", "-c", "emptyenv cd /home/bitcoinultras export HOME /home/bitcoinultras s6-setuidgid bitcoinultras /bin/bash"]
